title: Data Science Project Showcase
author:
  name: Guy
  email: Guy@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  1. Project Background
This project aims to develop a data-driven pricing strategy by analyzing the relationship between price and demand. The primary business objective is to optimize pricing to maximize revenue while maintaining competitive market positioning. The key problem statement is determining price elasticity and formulating an effective pricing adjustment strategy based on sales data and predictive modeling.

2. Work Accomplished
Data Preparation: Processed and cleaned the dataset, ensuring data consistency and handling missing values.
Model Selection & Training: Implemented multiple models, including Linear Regression, Random Forest, and Gradient Boosting, to predict demand based on price changes.
Model Evaluation: Evaluated the models’ accuracy, identifying Random Forest as the best-performing model. Further tuning using GridSearchCV improved its R² score from 0.4276 to 0.6018.
Price Elasticity Calculation: Estimated price elasticity by applying a 10% price adjustment and analyzing the impact on predicted demand.

3. Recommendation and Analysis
If a product has high price elasticity, a 10% price reduction is recommended to increase sales volume.
If a product has low price elasticity, a 10% price increase is recommended to maximize revenue.
If demand remains stable regardless of price changes, maintaining the current price is the best approach.
Due to potential biases from limited customer reviews, pricing strategies should be periodically reviewed with additional data sources.

4. AI Ethics
Privacy: The dataset does not contain personal customer information, ensuring compliance with privacy regulations.
Fairness: The pricing model is evaluated to prevent discrimination against specific customer groups or product categories.
Accuracy: The model’s predictions are continuously refined through data-driven insights and validation processes.
Accountability: Pricing decisions should be reviewed regularly, ensuring they align with business goals and market trends.
Transparency: The methodology, data sources, and model performance metrics are documented for stakeholder understanding and trust.

5. Source Codes and Datasets
The final modeling scripts and datasets have been uploaded to the project’s GitHub repository. The repository includes:

Final processed dataset used for training and evaluation
Python scripts for data preparation, modeling, and evaluation
Jupyter notebooks detailing the analysis and model training steps

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
#remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: classic
  
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #date_format: "%b-%d-%Y"

  # Generate social links in footer.
  #social_links:
  #  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #  - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #  - { platform: gitlab,         user_url: "https://gitlab.com/jekyll" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }


